# Generated by Django 2.2.16 on 2022-03-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
    ]
